"""
Intelligence Engine

Provides real-time AI-powered warnings and insights during 
research and investment decisions.

Features:
- Portfolio Conflict Checks (concentration, sector, correlation)
- Behavioral Pattern Detection (disposition effect, overconfidence, averaging down)
- Thesis Analysis (future)
- Similar Past Mistakes (future)

Usage:
    from app.services.intelligence_engine import IntelligenceEngine
    
    engine = IntelligenceEngine(user_id=123)
    warnings = engine.check_buy_transaction(company_id=456, amount=10000)
    
    for warning in warnings:
        print(f"[{warning.severity}] {warning.title}: {warning.message}")
"""

from typing import List, Optional, Dict, Any
from dataclasses import dataclass, field
import logging

from app.models.ai_intelligence import ResearchOutcome

try:
    import yfinance as yf
    YFINANCE_AVAILABLE = True
except ImportError:
    YFINANCE_AVAILABLE = False

from app.models import PortfolioPosition, Company, DecisionJournal, ResearchProject, ChecklistAnalysis, Transaction
from app.utils.financial_utils import calculate_cagr
from sqlalchemy.orm import joinedload
from app.constants import (
    # Concentration thresholds
    DEFAULT_POSITION_CONCENTRATION_THRESHOLD,
    DEFAULT_SECTOR_CONCENTRATION_THRESHOLD,
    DEFAULT_CORRELATION_THRESHOLD,
    # Run-up detection
    DEFAULT_RUNUP_LOOKBACK_DAYS,
    DEFAULT_RUNUP_THRESHOLD_PCT,
    # Chasing returns
    DEFAULT_CHASING_RETURNS_CAGR_THRESHOLD,
    DEFAULT_CHASING_RETURNS_MIN_DAYS,
)

# Import behavioral constants if they exist, otherwise use defaults
try:
    from app.constants import (
        DEFAULT_WINNER_THRESHOLD_PCT,
        DEFAULT_WINNER_MIN_HOLD_DAYS,
        DEFAULT_WINNER_EARLY_SELL_DAYS,
        DEFAULT_LOSER_THRESHOLD_PCT,
        DEFAULT_LOSER_HOLD_DAYS_WARNING,
        DEFAULT_LOSER_SEVERE_DAYS,
        DEFAULT_LOSER_SEVERE_PCT,
        DEFAULT_AVERAGING_DOWN_COUNT,
        DEFAULT_AVERAGING_DOWN_SEVERE_COUNT,
        DEFAULT_OVERCONFIDENCE_MIN_TRADES,
        DEFAULT_OVERCONFIDENCE_HIGH_CONFIDENCE,
        DEFAULT_OVERCONFIDENCE_POOR_OUTCOME_PCT,
        DEFAULT_OVERCONFIDENCE_POOR_RATE_THRESHOLD,
    )
except ImportError:
    # Fallback defaults if not yet added to constants.py
    DEFAULT_WINNER_THRESHOLD_PCT = 15.0
    DEFAULT_WINNER_MIN_HOLD_DAYS = 30
    DEFAULT_WINNER_EARLY_SELL_DAYS = 90
    DEFAULT_LOSER_THRESHOLD_PCT = -15.0
    DEFAULT_LOSER_HOLD_DAYS_WARNING = 180
    DEFAULT_LOSER_SEVERE_DAYS = 365
    DEFAULT_LOSER_SEVERE_PCT = -30.0
    DEFAULT_AVERAGING_DOWN_COUNT = 2
    DEFAULT_AVERAGING_DOWN_SEVERE_COUNT = 4
    DEFAULT_OVERCONFIDENCE_MIN_TRADES = 5
    DEFAULT_OVERCONFIDENCE_HIGH_CONFIDENCE = 8
    DEFAULT_OVERCONFIDENCE_POOR_OUTCOME_PCT = -10.0
    DEFAULT_OVERCONFIDENCE_POOR_RATE_THRESHOLD = 0.40
    
from app import db

logger = logging.getLogger(__name__)


@dataclass
class Warning:
    """A warning generated by the Intelligence Engine"""
    code: str                    # 'position_concentration', 'sector_overlap', etc.
    severity: str                # 'high', 'medium', 'low', 'info'
    category: str                # 'concentration', 'correlation', 'thesis', 'behavioral', 'research'
    title: str                   # Short title for display
    message: str                 # Detailed explanation
    data: Dict[str, Any] = field(default_factory=dict)  # Supporting data
    action_url: Optional[str] = None  # Link to take action
    dismissible: bool = True     # Can user dismiss this warning?


class IntelligenceEngine:
    """
    Main Intelligence Engine for generating investment warnings and insights.
    
    Currently uses hardcoded thresholds. Will be made configurable later.
    """
    
    # ═══════════════════════════════════════════════════════════════
    # HARDCODED THRESHOLDS (will be configurable via profiles later)
    # ═══════════════════════════════════════════════════════════════
    
    THRESHOLDS = {
        # Concentration warnings
        'position_concentration_pct': DEFAULT_POSITION_CONCENTRATION_THRESHOLD,
        'sector_concentration_pct': DEFAULT_SECTOR_CONCENTRATION_THRESHOLD,
        'industry_concentration_pct': 30.0,  # Not in constants yet
        
        # Correlation warnings
        'high_correlation_threshold': DEFAULT_CORRELATION_THRESHOLD / 100,  # Convert to decimal
        
        # Run-up detection
        'buying_after_runup_pct': DEFAULT_RUNUP_THRESHOLD_PCT,
        'runup_lookback_days': DEFAULT_RUNUP_LOOKBACK_DAYS,
        
        # Chasing returns
        'chasing_returns_cagr_threshold': DEFAULT_CHASING_RETURNS_CAGR_THRESHOLD,
        'chasing_returns_min_days': DEFAULT_CHASING_RETURNS_MIN_DAYS,
        
        # Disposition effect - selling winners
        'winner_threshold_pct': DEFAULT_WINNER_THRESHOLD_PCT,
        'winner_min_hold_days': DEFAULT_WINNER_MIN_HOLD_DAYS,
        'winner_early_sell_days': DEFAULT_WINNER_EARLY_SELL_DAYS,
        
        # Disposition effect - holding losers
        'loser_threshold_pct': DEFAULT_LOSER_THRESHOLD_PCT,
        'loser_hold_days_warning': DEFAULT_LOSER_HOLD_DAYS_WARNING,
        'loser_severe_days': DEFAULT_LOSER_SEVERE_DAYS,
        'loser_severe_pct': DEFAULT_LOSER_SEVERE_PCT,
        
        # Averaging down
        'averaging_down_count': DEFAULT_AVERAGING_DOWN_COUNT,
        'averaging_down_severe_count': DEFAULT_AVERAGING_DOWN_SEVERE_COUNT,
        
        # Overconfidence
        'overconfidence_min_trades': DEFAULT_OVERCONFIDENCE_MIN_TRADES,
        'overconfidence_high_confidence': DEFAULT_OVERCONFIDENCE_HIGH_CONFIDENCE,
        'overconfidence_poor_outcome_pct': DEFAULT_OVERCONFIDENCE_POOR_OUTCOME_PCT,
        'overconfidence_poor_rate_threshold': DEFAULT_OVERCONFIDENCE_POOR_RATE_THRESHOLD,
        
        # Research warnings
        'no_research_warning': True,
    }
    
    # Enabled rules (will be per-user configurable later)
    ENABLED_RULES = {
        # Concentration
        'position_concentration': True,
        'sector_concentration': True,
        'industry_concentration': False,
        'high_correlation': True,
        
        # Research
        'thesis_conflict': True,
        'no_research': True,
        
        # Behavioral - Buy side
        'buying_after_runup': True,
        'chasing_returns': True,
        'averaging_down': True,
        'overconfidence': True,
        
        # Behavioral - Sell side
        'selling_winner_early': True,
        'holding_loser_long': True,
    }
    
    def __init__(self, user_id: int):
        self.user_id = user_id
        self._portfolio_cache = None
        self._portfolio_value_cache = None
    
    # ═══════════════════════════════════════════════════════════════
    # MAIN API
    # ═══════════════════════════════════════════════════════════════
    
    def check_buy_transaction(
        self,
        company_id: int,
        amount: float,
        shares: Optional[float] = None,
        price_per_share: Optional[float] = None
    ) -> List[Warning]:
        """
        Check for warnings before a BUY transaction.
        
        Args:
            company_id: Company being purchased
            amount: Total dollar amount of purchase
            shares: Number of shares (optional)
            price_per_share: Price per share (optional)
            
        Returns:
            List of Warning objects
        """
        warnings = []
        
        company = Company.query.get(company_id)
        if not company:
            return warnings
        
        # Concentration checks
        if self.ENABLED_RULES.get('position_concentration'):
            warning = self._check_position_concentration(company, amount)
            if warning:
                warnings.append(warning)
        
        if self.ENABLED_RULES.get('sector_concentration'):
            warning = self._check_sector_concentration(company, amount)
            if warning:
                warnings.append(warning)
        
        if self.ENABLED_RULES.get('industry_concentration'):
            warning = self._check_industry_concentration(company, amount)
            if warning:
                warnings.append(warning)
        
        # Research checks
        if self.ENABLED_RULES.get('thesis_conflict'):
            warning = self._check_thesis_conflict(company)
            if warning:
                warnings.append(warning)
        
        if self.ENABLED_RULES.get('no_research'):
            warning = self._check_no_research(company)
            if warning:
                warnings.append(warning)
        
        # Behavioral checks - Buy side
        if self.ENABLED_RULES.get('buying_after_runup'):
            warning = self._check_buying_after_runup(company)
            if warning:
                warnings.append(warning)

        if self.ENABLED_RULES.get('chasing_returns'):
            warning = self._check_chasing_returns(company, amount)
            if warning:
                warnings.append(warning)
        
        if self.ENABLED_RULES.get('averaging_down'):
            warning = self._check_averaging_down(company, amount)
            if warning:
                warnings.append(warning)
        
        if self.ENABLED_RULES.get('overconfidence'):
            warning = self._check_overconfidence(company)
            if warning:
                warnings.append(warning)

        # Correlation check
        if self.ENABLED_RULES.get('high_correlation'):
            warning = self._check_high_correlation(company)
            if warning:
                warnings.append(warning)

        # Sort by severity
        severity_order = {'high': 0, 'medium': 1, 'low': 2, 'info': 3}
        warnings.sort(key=lambda w: severity_order.get(w.severity, 99))
        
        return warnings
    
    def get_portfolio_warnings(self) -> List[Warning]:
        """
        Get general portfolio-level warnings (not transaction-specific).
        
        Returns:
            List of Warning objects for portfolio health
        """
        warnings = []
        
        positions = self._get_portfolio_positions()
        portfolio_value = self._get_portfolio_value()
        
        if portfolio_value <= 0:
            return warnings
        
        # Check each position for concentration
        for position in positions:
            position_value = float(position.current_value or 0)
            position_pct = (position_value / portfolio_value) * 100
            
            if position_pct > self.THRESHOLDS['position_concentration_pct']:
                warnings.append(Warning(
                    code='existing_concentration',
                    severity='medium',
                    category='concentration',
                    title=f'{position.company.ticker_symbol} Concentration',
                    message=f'{position.company.ticker_symbol} is {position_pct:.1f}% of your portfolio. Consider rebalancing.',
                    data={
                        'ticker': position.company.ticker_symbol,
                        'percentage': position_pct,
                        'threshold': self.THRESHOLDS['position_concentration_pct']
                    }
                ))
        
        # Check sector concentration
        sector_totals = {}
        for position in positions:
            if position.company and position.company.sector:
                sector_name = position.company.sector.display_name
                sector_totals[sector_name] = sector_totals.get(sector_name, 0) + float(position.current_value or 0)
        
        for sector, total in sector_totals.items():
            sector_pct = (total / portfolio_value) * 100
            if sector_pct > self.THRESHOLDS['sector_concentration_pct']:
                warnings.append(Warning(
                    code='existing_sector_concentration',
                    severity='medium',
                    category='concentration',
                    title=f'{sector} Sector Heavy',
                    message=f'{sector} sector is {sector_pct:.1f}% of your portfolio.',
                    data={
                        'sector': sector,
                        'percentage': sector_pct,
                        'threshold': self.THRESHOLDS['sector_concentration_pct']
                    }
                ))
        
        return warnings
    
    def get_behavioral_insights(self) -> List[Warning]:
        """
        Get behavioral pattern insights for the user.
        
        Analyzes user's trading history to identify behavioral biases.
        Called from analytics/insights dashboard.
        
        Returns:
            List of behavioral insights/warnings
        """
        insights = []
        
        # Check overconfidence across all trades
        if self.ENABLED_RULES.get('overconfidence'):
            any_company = Company.query.filter_by(user_id=self.user_id).first()
            if any_company:
                warning = self._check_overconfidence(any_company)
                if warning:
                    insights.append(warning)
        
        # Check for losers being held too long
        if self.ENABLED_RULES.get('holding_loser_long'):
            positions = self._get_portfolio_positions()
            for position in positions:
                warning = self._check_holding_loser_long(position.company)
                if warning:
                    insights.append(warning)
        
        return insights
    
    # ═══════════════════════════════════════════════════════════════
    # CONCENTRATION CHECKS
    # ═══════════════════════════════════════════════════════════════
    
    def _check_position_concentration(self, company, amount: float) -> Optional[Warning]:
        """Check if this purchase would create concentration risk"""
        portfolio_value = self._get_portfolio_value()
        
        # Get existing position value
        existing_value = self._get_position_value(company.id)
        
        # Calculate new position percentage
        new_position_value = existing_value + amount
        new_portfolio_value = portfolio_value + amount
        
        if new_portfolio_value <= 0:
            return None
        
        new_position_pct = (new_position_value / new_portfolio_value) * 100
        threshold = self.THRESHOLDS['position_concentration_pct']
        
        if new_position_pct > threshold:
            # Determine severity based on how much over threshold
            if new_position_pct > threshold + 15:
                severity = 'high'
            elif new_position_pct > threshold + 5:
                severity = 'medium'
            else:
                severity = 'low'
            
            return Warning(
                code='position_concentration',
                severity=severity,
                category='concentration',
                title='Position Concentration Risk',
                message=f'This purchase would make {company.ticker_symbol} {new_position_pct:.1f}% of your portfolio (threshold: {threshold:.0f}%).',
                data={
                    'ticker': company.ticker_symbol,
                    'current_pct': (existing_value / portfolio_value * 100) if portfolio_value > 0 else 0,
                    'new_pct': new_position_pct,
                    'threshold': threshold,
                    'amount': amount
                }
            )
        
        return None
    
    def _check_sector_concentration(self, company, amount: float) -> Optional[Warning]:
        """Check if this purchase would create sector concentration"""
        if not company.sector:
            return None
        
        portfolio_value = self._get_portfolio_value()
        positions = self._get_portfolio_positions()
        
        sector_name = company.sector.display_name
        
        # Calculate current sector value
        current_sector_value = sum(
            float(p.current_value or 0)
            for p in positions
            if p.company and p.company.sector and p.company.sector.display_name == sector_name
        )
        
        # Calculate new sector percentage
        new_sector_value = current_sector_value + amount
        new_portfolio_value = portfolio_value + amount
        
        if new_portfolio_value <= 0:
            return None
        
        new_sector_pct = (new_sector_value / new_portfolio_value) * 100
        threshold = self.THRESHOLDS['sector_concentration_pct']
        
        if new_sector_pct > threshold:
            current_sector_pct = (current_sector_value / portfolio_value * 100) if portfolio_value > 0 else 0
            
            severity = 'high' if new_sector_pct > threshold + 10 else 'medium'
            
            return Warning(
                code='sector_concentration',
                severity=severity,
                category='concentration',
                title=f'{sector_name} Sector Concentration',
                message=f'This would bring {sector_name} to {new_sector_pct:.1f}% of your portfolio (threshold: {threshold:.0f}%).',
                data={
                    'sector': sector_name,
                    'current_pct': current_sector_pct,
                    'new_pct': new_sector_pct,
                    'threshold': threshold
                }
            )
        
        return None
    
    def _check_industry_concentration(self, company, amount: float) -> Optional[Warning]:
        """Check if this purchase would create industry concentration"""
        if not company.industry:
            return None
        
        portfolio_value = self._get_portfolio_value()
        positions = self._get_portfolio_positions()
        
        industry_name = company.industry
        
        # Calculate current industry value
        current_industry_value = sum(
            float(p.current_value or 0)
            for p in positions
            if p.company and p.company.industry == industry_name
        )
        
        # Calculate new industry percentage
        new_industry_value = current_industry_value + amount
        new_portfolio_value = portfolio_value + amount
        
        if new_portfolio_value <= 0:
            return None
        
        new_industry_pct = (new_industry_value / new_portfolio_value) * 100
        threshold = self.THRESHOLDS['industry_concentration_pct']
        
        if new_industry_pct > threshold:
            return Warning(
                code='industry_concentration',
                severity='medium',
                category='concentration',
                title=f'{industry_name} Industry Concentration',
                message=f'This would bring {industry_name} to {new_industry_pct:.1f}% of your portfolio.',
                data={
                    'industry': industry_name,
                    'new_pct': new_industry_pct,
                    'threshold': threshold
                }
            )
        
        return None
    
    # ═══════════════════════════════════════════════════════════════
    # RESEARCH CHECKS
    # ═══════════════════════════════════════════════════════════════
    
    def _check_thesis_conflict(self, company) -> Optional[Warning]:
        """Check if new purchase conflicts with existing thesis"""
        
        # Get existing positions and their theses
        positions = self._get_portfolio_positions()
        
        # Get the thesis for the company being purchased
        new_thesis_journal = DecisionJournal.query.filter_by(
            user_id=self.user_id,
            company_id=company.id,
            decision_type='BUY',
            is_portfolio_decision=True
        ).order_by(DecisionJournal.created_at.desc()).first()
        
        if not new_thesis_journal or not new_thesis_journal.investment_thesis:
            return None
        
        new_thesis = new_thesis_journal.investment_thesis.lower()
        
        # Simple conflict detection based on keywords
        # (In future, this could use Claude API for semantic analysis)
        
        conflicts = []
        
        for position in positions:
            if position.company_id == company.id:
                continue  # Skip same company
            
            # Get thesis for existing position
            existing_journal = DecisionJournal.query.filter_by(
                user_id=self.user_id,
                company_id=position.company_id,
                decision_type='BUY',
                is_portfolio_decision=True
            ).order_by(DecisionJournal.created_at.desc()).first()
            
            if not existing_journal or not existing_journal.investment_thesis:
                continue
            
            existing_thesis = existing_journal.investment_thesis.lower()
            
            # Check for potential conflicts (simplified keyword matching)
            # Example: Bullish on NVDA for "AI growth" but bearish on INTC thesis saying "AI commoditized"
            conflict_pairs = [
                (['bull', 'growth', 'increase', 'rise'], ['bear', 'decline', 'decrease', 'fall']),
                (['premium', 'pricing power'], ['commodity', 'race to bottom']),
                (['market leader', 'dominant'], ['losing share', 'disrupted']),
            ]
            
            for bullish_terms, bearish_terms in conflict_pairs:
                new_has_bullish = any(term in new_thesis for term in bullish_terms)
                existing_has_bearish = any(term in existing_thesis for term in bearish_terms)
                
                # Check if they're in same sector/industry (conflict more relevant)
                same_sector = (
                    company.sector and position.company.sector and
                    company.sector.id == position.company.sector.id
                )
                
                if new_has_bullish and existing_has_bearish and same_sector:
                    conflicts.append({
                        'ticker': position.company.ticker_symbol,
                        'thesis_snippet': existing_journal.investment_thesis[:100]
                    })
                    break
        
        if conflicts:
            return Warning(
                code='thesis_conflict',
                severity='medium',
                category='thesis',
                title='Potential Thesis Conflict',
                message=f'Your thesis for {company.ticker_symbol} may conflict with your thesis for {conflicts[0]["ticker"]}. Review both positions.',
                data={
                    'new_company': company.ticker_symbol,
                    'conflicting_positions': conflicts
                }
            )
        
        return None
    
    def _check_no_research(self, company) -> Optional[Warning]:
        """Check if buying without platform research"""
        if not self.THRESHOLDS.get('no_research_warning', True):
            return None
        
        # Check for completed research project
        research_project = ResearchProject.query.filter_by(
            user_id=self.user_id,
            company_id=company.id,
            status='completed'
        ).first()
        
        if research_project:
            return None
        
        # Check for completed checklist analysis
        checklist_analysis = ChecklistAnalysis.query.filter_by(
            user_id=self.user_id,
            company_id=company.id,
            status='completed'
        ).first()
        
        if checklist_analysis:
            return None
        
        # Check for active research
        active_research = ResearchProject.query.filter_by(
            user_id=self.user_id,
            company_id=company.id,
            status='active'
        ).first()
        
        if active_research:
            return Warning(
                code='research_incomplete',
                severity='medium',
                category='research',
                title='Research In Progress',
                message=f'You have active research on {company.ticker_symbol} that isn\'t complete. Consider finishing before buying.',
                data={
                    'ticker': company.ticker_symbol,
                    'research_id': active_research.id,
                    'progress': active_research.progress_percentage
                },
                action_url=f'/research/project/{active_research.id}'
            )
        
        # No research at all
        return Warning(
            code='no_research',
            severity='high',
            category='research',
            title='No Research Found',
            message=f'You haven\'t completed any research on {company.ticker_symbol}. Buying without research historically underperforms.',
            data={
                'ticker': company.ticker_symbol
            }
        )

    # ═══════════════════════════════════════════════════════════════
    # BEHAVIORAL CHECKS - BUY SIDE
    # ═══════════════════════════════════════════════════════════════
    
    def _check_buying_after_runup(self, company) -> Optional[Warning]:
        """
        Check if stock has run up significantly recently.
        Uses yfinance to fetch historical prices and detect FOMO-driven buying.
        """
        if not YFINANCE_AVAILABLE:
            return None  # yfinance not installed, skip this check

        try:
            lookback_days = self.THRESHOLDS['runup_lookback_days']
            threshold_pct = self.THRESHOLDS['buying_after_runup_pct']

            # Fetch historical data
            ticker = yf.Ticker(company.ticker_symbol)
            hist = ticker.history(period=f'{lookback_days}d')

            if hist.empty or len(hist) < 2:
                # Not enough data to check run-up
                return None

            # Get price from lookback_days ago and current price
            price_at_start = hist['Close'].iloc[0]
            current_price = hist['Close'].iloc[-1]

            # Calculate run-up percentage
            runup_pct = ((current_price - price_at_start) / price_at_start) * 100

            if runup_pct > threshold_pct:
                # Determine severity based on magnitude of run-up
                if runup_pct > threshold_pct * 2:  # 40%+ run-up in 30 days
                    severity = 'high'
                elif runup_pct > threshold_pct * 1.5:  # 30%+ run-up
                    severity = 'medium'
                else:
                    severity = 'low'

                return Warning(
                    code='buying_after_runup',
                    severity=severity,
                    category='behavioral',
                    title='Buying After Strong Run-Up',
                    message=f'{company.ticker_symbol} is up {runup_pct:.1f}% in the last {lookback_days} days. Consider if this is FOMO or based on fundamental thesis.',
                    data={
                        'ticker': company.ticker_symbol,
                        'runup_pct': round(runup_pct, 1),
                        'lookback_days': lookback_days,
                        'threshold': threshold_pct,
                        'price_at_start': round(float(price_at_start), 2),
                        'current_price': round(float(current_price), 2)
                    }
                )

            return None

        except Exception as e:
            logger.warning(f"Could not check run-up for {company.ticker_symbol}: {e}")
            return None

    def _check_chasing_returns(self, company, amount: float) -> Optional[Warning]:
        """
        Check if user is adding to a position with strong recent performance (CAGR).
        This helps identify potential FOMO or recency bias.
        """
        # Get existing position
        positions = self._get_portfolio_positions()
        existing_position = next((p for p in positions if p.company_id == company.id), None)

        if not existing_position:
            return None  # Not adding to existing position

        # Only check if position has been held long enough for CAGR to be meaningful
        days_held = existing_position.days_held or 0
        min_days = self.THRESHOLDS['chasing_returns_min_days']

        if days_held < min_days:
            return None  # Position too new for meaningful CAGR analysis

        # Calculate CAGR
        total_return = float(existing_position.unrealized_gain_loss_pct or 0)
        cagr = calculate_cagr(total_return, days_held)

        threshold_cagr = self.THRESHOLDS['chasing_returns_cagr']

        if cagr > threshold_cagr:
            # Determine severity based on how much CAGR exceeds threshold
            if cagr > threshold_cagr * 1.5:  # 75%+ CAGR
                severity = 'high'
            elif cagr > threshold_cagr * 1.2:  # 60%+ CAGR
                severity = 'medium'
            else:
                severity = 'low'

            return Warning(
                code='chasing_hot_position',
                severity=severity,
                category='behavioral',
                title='Adding to Hot Position',
                message=f'{company.ticker_symbol} has returned {cagr:.1f}% annualized ({total_return:.1f}% total over {days_held} days). Are you chasing performance or adding based on thesis?',
                data={
                    'ticker': company.ticker_symbol,
                    'cagr': cagr,
                    'total_return': total_return,
                    'days_held': days_held,
                    'threshold': threshold_cagr,
                    'adding_amount': amount,
                    'current_position_value': float(existing_position.current_value or 0)
                }
            )

        return None

    def _check_averaging_down(self, company, amount: float) -> Optional[Warning]:
        """Check if user is averaging down into a losing position repeatedly"""
        positions = self._get_portfolio_positions()
        existing_position = next((p for p in positions if p.company_id == company.id), None)

        if not existing_position:
            return None

        current_return = float(existing_position.unrealized_gain_loss_pct or 0)

        if current_return >= 0:
            return None

        previous_buys = Transaction.query.filter_by(
            user_id=self.user_id,
            company_id=company.id,
            type='BUY'
        ).count()

        avg_down_threshold = self.THRESHOLDS['averaging_down_count']
        severe_threshold = self.THRESHOLDS['averaging_down_severe_count']

        if previous_buys >= avg_down_threshold:
            avg_cost = float(existing_position.average_cost_basis or 0)
            current_price = float(existing_position.current_price or 0)

            if current_price < avg_cost:
                severity = 'high' if previous_buys >= severe_threshold else 'medium'
                
                ordinal = lambda n: f"{n}{'th' if 11<=n<=13 else {1:'st',2:'nd',3:'rd'}.get(n%10,'th')}"

                return Warning(
                    code='averaging_down',
                    severity=severity,
                    category='behavioral',
                    title='Repeated Averaging Down',
                    message=(
                        f'This would be your {ordinal(previous_buys + 1)} buy into {company.ticker_symbol}, '
                        f'which is down {abs(current_return):.1f}%. Multiple averaging down often indicates hope over thesis.'
                    ),
                    data={
                        'ticker': company.ticker_symbol,
                        'current_return': current_return,
                        'previous_buys': previous_buys,
                        'avg_cost': avg_cost,
                        'current_price': current_price,
                        'adding_amount': amount,
                        'current_position_value': float(existing_position.current_value or 0)
                    }
                )

        return None

    def _check_overconfidence(self, company) -> Optional[Warning]:
        """Check if user shows overconfidence pattern"""
        min_trades = self.THRESHOLDS['overconfidence_min_trades']
        high_confidence = self.THRESHOLDS['overconfidence_high_confidence']
        poor_outcome_pct = self.THRESHOLDS['overconfidence_poor_outcome_pct']
        poor_rate_threshold = self.THRESHOLDS['overconfidence_poor_rate_threshold']

        outcomes = ResearchOutcome.query.filter(
            ResearchOutcome.user_id == self.user_id,
            ResearchOutcome.realized_return_pct.isnot(None),
            ResearchOutcome.decision_confidence.isnot(None)
        ).all()

        if len(outcomes) < min_trades:
            return None

        high_conf_outcomes = [
            o for o in outcomes 
            if o.decision_confidence >= high_confidence
        ]

        if len(high_conf_outcomes) < 3:
            return None

        high_conf_returns = [float(o.realized_return_pct) for o in high_conf_outcomes]
        high_conf_avg = sum(high_conf_returns) / len(high_conf_returns)
        high_conf_poor = len([r for r in high_conf_returns if r <= poor_outcome_pct])
        high_conf_poor_rate = high_conf_poor / len(high_conf_outcomes)

        all_returns = [float(o.realized_return_pct) for o in outcomes]
        all_avg = sum(all_returns) / len(all_returns)

        is_overconfident = (
            (high_conf_avg < all_avg - 5) or
            (high_conf_poor_rate > poor_rate_threshold)
        )

        if is_overconfident:
            current_journal = DecisionJournal.query.filter_by(
                user_id=self.user_id,
                company_id=company.id,
                decision_type='BUY',
                is_portfolio_decision=True
            ).order_by(DecisionJournal.created_at.desc()).first()

            current_confidence = current_journal.confidence_score if current_journal else None
            severity = 'medium' if high_conf_poor_rate > 0.5 else 'low'

            return Warning(
                code='overconfidence_pattern',
                severity=severity,
                category='behavioral',
                title='Overconfidence Pattern Detected',
                message=(
                    f'Your high-confidence decisions (8+) have averaged {high_conf_avg:.1f}% returns '
                    f'vs {all_avg:.1f}% overall. {high_conf_poor_rate*100:.0f}% of high-confidence '
                    f'trades had poor outcomes. Consider tempering confidence.'
                ),
                data={
                    'high_conf_avg_return': high_conf_avg,
                    'overall_avg_return': all_avg,
                    'high_conf_poor_rate': high_conf_poor_rate,
                    'high_conf_count': len(high_conf_outcomes),
                    'total_trades': len(outcomes),
                    'current_confidence': current_confidence,
                    'confidence_threshold': high_confidence
                }
            )

        return None

    # ═══════════════════════════════════════════════════════════════
    # BEHAVIORAL CHECKS - SELL SIDE
    # ═══════════════════════════════════════════════════════════════
    
    def _check_selling_winner_early(self, company, shares_to_sell: int) -> Optional[Warning]:
        """Check if user is selling a winning position too early (disposition effect)"""
        positions = self._get_portfolio_positions()
        position = next((p for p in positions if p.company_id == company.id), None)

        if not position:
            return None

        gain_pct = float(position.unrealized_gain_loss_pct or 0)
        days_held = position.days_held or 0

        winner_threshold = self.THRESHOLDS['winner_threshold_pct']
        early_sell_days = self.THRESHOLDS['winner_early_sell_days']

        if gain_pct >= winner_threshold and days_held < early_sell_days:
            is_full_exit = shares_to_sell >= position.total_shares

            journal = DecisionJournal.query.filter_by(
                user_id=self.user_id,
                company_id=company.id,
                decision_type='BUY',
                is_portfolio_decision=True
            ).order_by(DecisionJournal.created_at.desc()).first()

            has_thesis = journal and journal.investment_thesis

            if is_full_exit:
                severity = 'medium'
                action_msg = "You're exiting completely."
            else:
                severity = 'low'
                action_msg = f"You're selling {shares_to_sell} of {position.total_shares} shares."

            message = (
                f'{company.ticker_symbol} is up {gain_pct:.1f}% after only {days_held} days. '
                f'{action_msg} Winners often keep winning - is your thesis broken, or are you locking in gains too early?'
            )

            return Warning(
                code='selling_winner_early',
                severity=severity,
                category='behavioral',
                title='Selling Winner Early?',
                message=message,
                data={
                    'ticker': company.ticker_symbol,
                    'gain_pct': gain_pct,
                    'days_held': days_held,
                    'shares_selling': shares_to_sell,
                    'total_shares': position.total_shares,
                    'is_full_exit': is_full_exit,
                    'has_thesis': has_thesis,
                    'winner_threshold': winner_threshold,
                    'early_sell_days': early_sell_days
                }
            )

        return None
    
    def _check_holding_loser_long(self, company) -> Optional[Warning]:
        """Check if user has been holding a losing position too long"""
        positions = self._get_portfolio_positions()
        position = next((p for p in positions if p.company_id == company.id), None)

        if not position:
            return None

        loss_pct = float(position.unrealized_gain_loss_pct or 0)
        days_held = position.days_held or 0

        loser_threshold = self.THRESHOLDS['loser_threshold_pct']
        hold_days_warning = self.THRESHOLDS['loser_hold_days_warning']
        severe_days = self.THRESHOLDS['loser_severe_days']
        severe_pct = self.THRESHOLDS['loser_severe_pct']

        if loss_pct <= loser_threshold and days_held >= hold_days_warning:
            journal = DecisionJournal.query.filter_by(
                user_id=self.user_id,
                company_id=company.id,
                decision_type='BUY',
                is_portfolio_decision=True
            ).order_by(DecisionJournal.created_at.desc()).first()

            if loss_pct <= severe_pct and days_held >= severe_days:
                severity = 'high'
            elif loss_pct <= severe_pct or days_held >= severe_days * 0.75:
                severity = 'medium'
            else:
                severity = 'low'

            return Warning(
                code='holding_loser_long',
                severity=severity,
                category='behavioral',
                title='Holding Loser Too Long?',
                message=(
                    f'{company.ticker_symbol} is down {abs(loss_pct):.1f}% after {days_held} days. '
                    f'Is your original thesis still valid, or are you hoping it will recover?'
                ),
                data={
                    'ticker': company.ticker_symbol,
                    'loss_pct': loss_pct,
                    'days_held': days_held,
                    'loser_threshold': loser_threshold,
                    'hold_days_warning': hold_days_warning,
                    'has_thesis': bool(journal and journal.investment_thesis)
                },
                action_url=f'/portfolio/position/{position.id}'
            )

        return None

    # ═══════════════════════════════════════════════════════════════
    # CORRELATION CHECK
    # ═══════════════════════════════════════════════════════════════

    def _check_high_correlation(self, company) -> Optional[Warning]:
        """Check if new stock is highly correlated with existing positions"""
        positions = self._get_portfolio_positions()

        same_industry_positions = []
        same_sector_positions = []

        for p in positions:
            if not p.company or p.company_id == company.id:
                continue

            if company.industry and p.company.industry == company.industry:
                same_industry_positions.append(p)
            elif company.sector and p.company.sector and p.company.sector.id == company.sector.id:
                same_sector_positions.append(p)

        if len(same_industry_positions) >= 2:
            tickers = [p.company.ticker_symbol for p in same_industry_positions[:3]]
            industry_name = company.industry or 'same industry'

            return Warning(
                code='high_correlation_industry',
                severity='medium',
                category='correlation',
                title='Same Industry Concentration',
                message=f'{company.ticker_symbol} is in {industry_name}, where you already own {len(same_industry_positions)} positions: {", ".join(tickers)}. Industry-specific risks may be concentrated.',
                data={
                    'ticker': company.ticker_symbol,
                    'industry': industry_name,
                    'correlated_count': len(same_industry_positions),
                    'correlated_tickers': tickers
                }
            )

        if len(same_sector_positions) >= 3:
            tickers = [p.company.ticker_symbol for p in same_sector_positions[:3]]
            sector_name = company.sector.display_name if company.sector else 'same sector'

            return Warning(
                code='high_correlation_sector',
                severity='low',
                category='correlation',
                title='Sector Overlap',
                message=f'{company.ticker_symbol} is in {sector_name}, where you already own {len(same_sector_positions)} positions. These stocks may be correlated.',
                data={
                    'ticker': company.ticker_symbol,
                    'sector': sector_name,
                    'correlated_count': len(same_sector_positions),
                    'correlated_tickers': [p.company.ticker_symbol for p in same_sector_positions]
                }
            )

        return None
    
    # ═══════════════════════════════════════════════════════════════
    # HELPER METHODS
    # ═══════════════════════════════════════════════════════════════
    
    def _get_portfolio_positions(self):
        """Get all active portfolio positions (cached with eager loading)"""
        if self._portfolio_cache is None:
            self._portfolio_cache = PortfolioPosition.query.filter_by(
                user_id=self.user_id,
                is_active=True
            ).options(
                joinedload(PortfolioPosition.company).joinedload(Company.sector)
            ).all()
        return self._portfolio_cache
    
    def _get_portfolio_value(self) -> float:
        """Get total portfolio value (cached)"""
        if self._portfolio_value_cache is None:
            positions = self._get_portfolio_positions()
            self._portfolio_value_cache = sum(
                float(p.current_value or 0) for p in positions
            )
        return self._portfolio_value_cache
    
    def _get_position_value(self, company_id: int) -> float:
        """Get current value of a specific position"""
        positions = self._get_portfolio_positions()
        position = next((p for p in positions if p.company_id == company_id), None)
        return float(position.current_value or 0) if position else 0.0
    
    def clear_cache(self):
        """Clear cached data (call after portfolio changes)"""
        self._portfolio_cache = None
        self._portfolio_value_cache = None


# ═══════════════════════════════════════════════════════════════
# CONVENIENCE FUNCTIONS
# ═══════════════════════════════════════════════════════════════

def check_buy_warnings(user_id: int, company_id: int, amount: float) -> List[Warning]:
    """Check for warnings before a BUY transaction."""
    engine = IntelligenceEngine(user_id)
    return engine.check_buy_transaction(company_id, amount)


def check_sell_warnings(user_id: int, company_id: int, shares: int) -> List[Warning]:
    """Check for warnings before a SELL transaction."""
    engine = IntelligenceEngine(user_id)
    return engine.check_sell_transaction(company_id, shares)


def get_portfolio_warnings(user_id: int) -> List[Warning]:
    """Get general portfolio warnings."""
    engine = IntelligenceEngine(user_id)
    return engine.get_portfolio_warnings()


def get_behavioral_insights(user_id: int) -> List[Warning]:
    """Get behavioral pattern insights for a user."""
    engine = IntelligenceEngine(user_id)
    return engine.get_behavioral_insights()