"""Initial PostgreSQL migration

Revision ID: 02c0d68cf3c2
Revises: 
Create Date: 2025-09-16 15:21:01.166249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c0d68cf3c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('intrinsic_value', sa.BigInteger(), nullable=True),
    sa.Column('is_in_portfolio', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_is_in_portfolio'), ['is_in_portfolio'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_ticker_symbol'), ['ticker_symbol'], unique=False)

    op.create_table('idea_source_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('total_ideas', sa.Integer(), nullable=True),
    sa.Column('ideas_killed', sa.Integer(), nullable=True),
    sa.Column('ideas_promoted', sa.Integer(), nullable=True),
    sa.Column('ideas_invested', sa.Integer(), nullable=True),
    sa.Column('survival_rate', sa.Float(), nullable=True),
    sa.Column('investment_rate', sa.Float(), nullable=True),
    sa.Column('average_research_hours', sa.Float(), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('successful_investments', sa.Integer(), nullable=True),
    sa.Column('failed_investments', sa.Integer(), nullable=True),
    sa.Column('average_return', sa.Float(), nullable=True),
    sa.Column('last_idea_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_name', name='_user_source_uc')
    )
    op.create_table('journal_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('prompts', sa.JSON(), nullable=True),
    sa.Column('required_fields', sa.JSON(), nullable=True),
    sa.Column('example_content', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kill_checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('applicable_to', sa.String(length=100), nullable=True),
    sa.Column('total_ideas_evaluated', sa.Integer(), nullable=True),
    sa.Column('total_ideas_killed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill_area', sa.String(length=100), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('completed_steps', sa.Integer(), nullable=True),
    sa.Column('learning_resources', sa.JSON(), nullable=True),
    sa.Column('practice_exercises', sa.JSON(), nullable=True),
    sa.Column('milestones', sa.JSON(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('progress_notes', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('target_completion', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pattern_recognition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pattern_name', sa.String(length=200), nullable=False),
    sa.Column('pattern_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('financial_impact', sa.Text(), nullable=True),
    sa.Column('how_to_leverage', sa.Text(), nullable=True),
    sa.Column('how_to_avoid', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('needs_more_data', sa.Boolean(), nullable=True),
    sa.Column('identified_date', sa.Date(), nullable=True),
    sa.Column('last_observed', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_bank_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('llm_prompt', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_bank_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_bank_item_sector'), ['sector'], unique=False)

    op.create_table('research_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_ideas_captured', sa.Integer(), nullable=True),
    sa.Column('ideas_killed', sa.Integer(), nullable=True),
    sa.Column('ideas_promoted', sa.Integer(), nullable=True),
    sa.Column('ideas_in_pipeline', sa.Integer(), nullable=True),
    sa.Column('average_days_to_decision', sa.Float(), nullable=True),
    sa.Column('kill_rate', sa.Float(), nullable=True),
    sa.Column('most_common_kill_reason', sa.String(length=500), nullable=True),
    sa.Column('fastest_kill_minutes', sa.Integer(), nullable=True),
    sa.Column('slowest_kill_minutes', sa.Integer(), nullable=True),
    sa.Column('total_research_hours', sa.Float(), nullable=True),
    sa.Column('average_hours_per_company', sa.Float(), nullable=True),
    sa.Column('average_hours_per_decision', sa.Float(), nullable=True),
    sa.Column('most_time_consuming_step', sa.String(length=200), nullable=True),
    sa.Column('total_investment_decisions', sa.Integer(), nullable=True),
    sa.Column('invest_decisions', sa.Integer(), nullable=True),
    sa.Column('pass_decisions', sa.Integer(), nullable=True),
    sa.Column('average_confidence_score', sa.Float(), nullable=True),
    sa.Column('winning_investments', sa.Integer(), nullable=True),
    sa.Column('losing_investments', sa.Integer(), nullable=True),
    sa.Column('average_return', sa.Float(), nullable=True),
    sa.Column('best_investment_return', sa.Float(), nullable=True),
    sa.Column('worst_investment_return', sa.Float(), nullable=True),
    sa.Column('best_idea_source', sa.String(length=200), nullable=True),
    sa.Column('best_source_success_rate', sa.Float(), nullable=True),
    sa.Column('most_productive_day', sa.String(length=20), nullable=True),
    sa.Column('most_productive_hour', sa.Integer(), nullable=True),
    sa.Column('average_session_duration', sa.Float(), nullable=True),
    sa.Column('research_streak_days', sa.Integer(), nullable=True),
    sa.Column('last_research_date', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('research_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('investment_style', sa.String(length=100), nullable=True),
    sa.Column('research_subject_types', sa.JSON(), nullable=True),
    sa.Column('workflow_steps', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('successful_investments', sa.Integer(), nullable=True),
    sa.Column('failed_investments', sa.Integer(), nullable=True),
    sa.Column('average_research_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sector_name', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sector_name', name='uq_user_sector')
    )
    with op.batch_alter_table('sector_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sector_analysis_sector_name'), ['sector_name'], unique=False)

    op.create_table('template_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('common_pitfalls', sa.Text(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('average_actual_minutes', sa.Float(), nullable=True),
    sa.Column('skip_rate', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('ideas_captured', sa.Integer(), nullable=True),
    sa.Column('ideas_killed', sa.Integer(), nullable=True),
    sa.Column('research_hours', sa.Float(), nullable=True),
    sa.Column('decisions_made', sa.Integer(), nullable=True),
    sa.Column('biggest_win', sa.Text(), nullable=True),
    sa.Column('biggest_challenge', sa.Text(), nullable=True),
    sa.Column('key_learnings', sa.JSON(), nullable=True),
    sa.Column('market_thoughts', sa.Text(), nullable=True),
    sa.Column('opportunities_identified', sa.JSON(), nullable=True),
    sa.Column('risks_identified', sa.JSON(), nullable=True),
    sa.Column('next_week_priorities', sa.JSON(), nullable=True),
    sa.Column('companies_to_research', sa.JSON(), nullable=True),
    sa.Column('last_week_goals_achieved', sa.JSON(), nullable=True),
    sa.Column('goals_completion_rate', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('market_sentiment', sa.String(length=50), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('llm_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['checklist_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('company_article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_article_published_at'), ['published_at'], unique=False)

    op.create_table('company_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=300), nullable=False),
    sa.Column('document_group', sa.String(length=100), nullable=False),
    sa.Column('document_title', sa.String(length=255), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('company_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_document_document_group'), ['document_group'], unique=False)

    op.create_table('competitors_association',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['competitor_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'competitor_id')
    )
    op.create_table('destination_checkpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=200), nullable=False),
    sa.Column('expectation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destination_checkpoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_destination_checkpoint_target_date'), ['target_date'], unique=False)

    op.create_table('favorite_companies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    op.create_table('financial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'metric_name', 'period_date', name='uq_company_metric_period')
    )
    with op.batch_alter_table('financial_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_data_metric_name'), ['metric_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_data_period_date'), ['period_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_data_statement_type'), ['statement_type'], unique=False)

    op.create_table('kill_criterion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kill_checklist_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('times_evaluated', sa.Integer(), nullable=True),
    sa.Column('times_failed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kill_checklist_id'], ['kill_checklist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualitative_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', 'model_type', name='uq_user_company_analysis')
    )
    with op.batch_alter_table('qualitative_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualitative_analysis_model_type'), ['model_type'], unique=False)

    op.create_table('research_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scuttlebutt_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('generated_summary', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scuttlebutt_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scuttlebutt_analysis_generated_at'), ['generated_at'], unique=False)

    op.create_table('idea_pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('idea_type', sa.String(length=50), nullable=False),
    sa.Column('idea_purpose', sa.String(length=50), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('thesis_summary', sa.Text(), nullable=True),
    sa.Column('initial_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('kill_reason', sa.Text(), nullable=True),
    sa.Column('failed_criterion_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('killed_at', sa.DateTime(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('promoted_to_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['failed_criterion_id'], ['kill_criterion.id'], ),
    sa.ForeignKeyConstraint(['promoted_to_company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idea_pipeline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_pipeline_status'), ['status'], unique=False)

    op.create_table('research_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('satisfaction_status', sa.String(length=30), nullable=True),
    sa.Column('research_session_id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_item.id'], ),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kill_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('kill_checklist_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['idea_pipeline.id'], ),
    sa.ForeignKeyConstraint(['kill_checklist_id'], ['kill_checklist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('research_subject_type', sa.String(length=50), nullable=False),
    sa.Column('research_subject_name', sa.String(length=200), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('investment_thesis', sa.Text(), nullable=True),
    sa.Column('current_step_index', sa.Integer(), nullable=True),
    sa.Column('completed_steps', sa.JSON(), nullable=True),
    sa.Column('step_notes', sa.JSON(), nullable=True),
    sa.Column('step_results', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('kill_reason', sa.Text(), nullable=True),
    sa.Column('total_hours_spent', sa.Float(), nullable=True),
    sa.Column('time_per_step', sa.JSON(), nullable=True),
    sa.Column('last_worked_at', sa.DateTime(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('decision_confidence', sa.Integer(), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('investment_amount', sa.Float(), nullable=True),
    sa.Column('investment_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('return_percentage', sa.Float(), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('red_flags', sa.JSON(), nullable=True),
    sa.Column('green_flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['idea_id'], ['idea_pipeline.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['research_template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('decision_type', sa.String(length=20), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('investment_thesis', sa.Text(), nullable=True),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('expected_timeframe', sa.Integer(), nullable=True),
    sa.Column('key_assumptions', sa.JSON(), nullable=True),
    sa.Column('biggest_risks', sa.JSON(), nullable=True),
    sa.Column('exit_criteria', sa.Text(), nullable=True),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('actual_timeframe', sa.Integer(), nullable=True),
    sa.Column('outcome_date', sa.Date(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('what_went_right', sa.Text(), nullable=True),
    sa.Column('what_went_wrong', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('would_repeat', sa.Boolean(), nullable=True),
    sa.Column('mistake_category', sa.String(length=100), nullable=True),
    sa.Column('success_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('key_insight', sa.Text(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('questions_raised', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('conviction_level', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['idea_id'], ['idea_pipeline.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_created_at'), ['created_at'], unique=False)

    op.create_table('kill_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kill_session_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['kill_criterion.id'], ),
    sa.ForeignKeyConstraint(['kill_session_id'], ['kill_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['idea_id'], ['idea_pipeline.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('work_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(length=200), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('documents_reviewed', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('needs_followup', sa.Boolean(), nullable=True),
    sa.Column('followup_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['research_project_id'], ['research_project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_postmortem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=False),
    sa.Column('holding_period_days', sa.Integer(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('annualized_return', sa.Float(), nullable=True),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('thesis_accuracy', sa.String(length=50), nullable=True),
    sa.Column('thesis_playing_out', sa.Text(), nullable=True),
    sa.Column('unexpected_developments', sa.JSON(), nullable=True),
    sa.Column('decision_quality_score', sa.Integer(), nullable=True),
    sa.Column('process_followed', sa.Boolean(), nullable=True),
    sa.Column('emotional_factors', sa.Text(), nullable=True),
    sa.Column('what_went_well', sa.JSON(), nullable=True),
    sa.Column('what_went_poorly', sa.JSON(), nullable=True),
    sa.Column('lucky_breaks', sa.JSON(), nullable=True),
    sa.Column('primary_lesson', sa.Text(), nullable=True),
    sa.Column('secondary_lessons', sa.JSON(), nullable=True),
    sa.Column('process_improvements', sa.JSON(), nullable=True),
    sa.Column('would_repeat', sa.Boolean(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_journal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('how_to_apply', sa.Text(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('anti_examples', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_detail', sa.String(length=200), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('times_reviewed', sa.Integer(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('review_interval_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_journal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mistake_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mistake_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('occurred_date', sa.Date(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('lesson_learned', sa.Text(), nullable=False),
    sa.Column('prevention_steps', sa.JSON(), nullable=True),
    sa.Column('process_changes', sa.Text(), nullable=True),
    sa.Column('times_reviewed', sa.Integer(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('prevented_similar', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_journal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis_evolution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('change_trigger', sa.String(length=200), nullable=True),
    sa.Column('conviction_level', sa.Integer(), nullable=True),
    sa.Column('position_sizing', sa.String(length=50), nullable=True),
    sa.Column('bull_case', sa.JSON(), nullable=True),
    sa.Column('bear_case', sa.JSON(), nullable=True),
    sa.Column('key_metrics', sa.JSON(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('linked_journal_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['linked_journal_entry_id'], ['journal_entry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thesis_evolution')
    op.drop_table('mistake_log')
    op.drop_table('learning_note')
    op.drop_table('journal_attachment')
    op.drop_table('investment_postmortem')
    op.drop_table('work_session')
    with op.batch_alter_table('research_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_log_timestamp'))

    op.drop_table('research_log')
    op.drop_table('kill_answer')
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_created_at'))

    op.drop_table('journal_entry')
    op.drop_table('decision_journal')
    op.drop_table('research_project')
    op.drop_table('kill_session')
    op.drop_table('research_answer')
    with op.batch_alter_table('idea_pipeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_pipeline_status'))

    op.drop_table('idea_pipeline')
    with op.batch_alter_table('scuttlebutt_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scuttlebutt_analysis_generated_at'))

    op.drop_table('scuttlebutt_analysis')
    op.drop_table('research_session')
    with op.batch_alter_table('qualitative_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualitative_analysis_model_type'))

    op.drop_table('qualitative_analysis')
    op.drop_table('kill_criterion')
    with op.batch_alter_table('financial_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_data_statement_type'))
        batch_op.drop_index(batch_op.f('ix_financial_data_period_date'))
        batch_op.drop_index(batch_op.f('ix_financial_data_metric_name'))

    op.drop_table('financial_data')
    op.drop_table('favorite_companies')
    with op.batch_alter_table('destination_checkpoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destination_checkpoint_target_date'))

    op.drop_table('destination_checkpoint')
    op.drop_table('competitors_association')
    with op.batch_alter_table('company_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_document_document_group'))

    op.drop_table('company_document')
    with op.batch_alter_table('company_article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_article_published_at'))

    op.drop_table('company_article')
    op.drop_table('checklist_item')
    op.drop_table('weekly_review')
    op.drop_table('template_step')
    with op.batch_alter_table('sector_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_analysis_sector_name'))

    op.drop_table('sector_analysis')
    op.drop_table('research_template')
    op.drop_table('research_metrics')
    with op.batch_alter_table('question_bank_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_bank_item_sector'))

    op.drop_table('question_bank_item')
    op.drop_table('pattern_recognition')
    op.drop_table('learning_path')
    op.drop_table('kill_checklist')
    op.drop_table('journal_template')
    op.drop_table('idea_source_analysis')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_ticker_symbol'))
        batch_op.drop_index(batch_op.f('ix_company_is_in_portfolio'))

    op.drop_table('company')
    op.drop_table('checklist')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
