"""Add step_overrides to ResearchProject for deleted checklist recovery

Revision ID: 0b58d4f1ab37
Revises: 0cdbd6595f65
Create Date: 2025-10-18 15:51:15.770337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b58d4f1ab37'
down_revision = '0cdbd6595f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_overrides', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_project', schema=None) as batch_op:
        batch_op.drop_column('step_overrides')

    # ### end Alembic commands ###
