"""Add company tagging for sector notes and snippets

Revision ID: 0cdbd6595f65
Revises: replace_notes_document
Create Date: 2025-10-09 20:41:50.923031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdbd6595f65'
down_revision = 'replace_notes_document'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector_snippet_companies',
    sa.Column('sector_snippet_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['sector_snippet_id'], ['sector_research_snippet.id'], ),
    sa.PrimaryKeyConstraint('sector_snippet_id', 'company_id')
    )
    op.create_table('sector_note_companies',
    sa.Column('sector_note_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['sector_note_id'], ['sector_note.id'], ),
    sa.PrimaryKeyConstraint('sector_note_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sector_note_companies')
    op.drop_table('sector_snippet_companies')
    # ### end Alembic commands ###
