"""Add AI research feedback table for tracking interactions and user feedback

Revision ID: 109bc6695111
Revises: 155df2cb043d
Create Date: 2026-01-17 20:06:45.943275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109bc6695111'
down_revision = '155df2cb043d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_research_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.String(length=20), nullable=True),
    sa.Column('feedback_at', sa.DateTime(), nullable=True),
    sa.Column('answer_revised', sa.Boolean(), nullable=True),
    sa.Column('revised_answer', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['checklist_analysis.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_research_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_research_feedback_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_research_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_research_feedback_feedback'), ['feedback'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_research_feedback_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_research_feedback_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_research_feedback_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_research_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_research_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_research_feedback_mode'))
        batch_op.drop_index(batch_op.f('ix_ai_research_feedback_item_id'))
        batch_op.drop_index(batch_op.f('ix_ai_research_feedback_feedback'))
        batch_op.drop_index(batch_op.f('ix_ai_research_feedback_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_research_feedback_analysis_id'))

    op.drop_table('ai_research_feedback')
    # ### end Alembic commands ###
