"""Add prompt management tables (PromptVersion, PromptUsageLog)

Revision ID: 155df2cb043d
Revises: 8738fe6620b7
Create Date: 2026-01-02 20:55:59.403655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155df2cb043d'
down_revision = '8738fe6620b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('system_context', sa.Text(), nullable=True),
    sa.Column('preferred_provider', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_version_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_version_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_version_name'), ['name'], unique=False)

    op.create_table('prompt_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_version_id', sa.Integer(), nullable=True),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_cents', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_version.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_usage_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_usage_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_usage_log_prompt_name'), ['prompt_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_usage_log_prompt_version_id'), ['prompt_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_usage_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('system_config_key_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_system_config_key'))
        batch_op.create_index(batch_op.f('ix_system_config_key'), ['key'], unique=True)

    with op.batch_alter_table('user_investment_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_investment_profile_user_id'))
        batch_op.drop_constraint(batch_op.f('user_investment_profile_profile_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_investment_profile_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'investor_profile', ['profile_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_investment_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_investment_profile_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('user_investment_profile_profile_id_fkey'), 'investor_profile', ['profile_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_user_investment_profile_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_config_key'))
        batch_op.create_index(batch_op.f('ix_system_config_key'), ['key'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('system_config_key_key'), ['key'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('prompt_usage_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_usage_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_usage_log_prompt_version_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_usage_log_prompt_name'))
        batch_op.drop_index(batch_op.f('ix_prompt_usage_log_created_at'))

    op.drop_table('prompt_usage_log')
    with op.batch_alter_table('prompt_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_version_name'))
        batch_op.drop_index(batch_op.f('ix_prompt_version_is_active'))
        batch_op.drop_index(batch_op.f('ix_prompt_version_category'))

    op.drop_table('prompt_version')
    # ### end Alembic commands ###
