"""Add created_at and updated_at to Checklist model

Revision ID: 39fd8c94a6c5
Revises: add_sector_status_tracking
Create Date: 2025-10-08 19:23:01.288672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fd8c94a6c5'
down_revision = 'add_sector_status_tracking'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add timestamp columns as nullable first
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # Set default timestamps for existing records
    op.execute("UPDATE checklist SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE checklist SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL")

    # Make columns non-nullable
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)
        batch_op.alter_column('updated_at', nullable=False)

    with op.batch_alter_table('sector_research_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_research_section_display_order'))
        batch_op.drop_index(batch_op.f('ix_sector_research_section_sector_analysis_id'))
        batch_op.drop_constraint(batch_op.f('sector_research_section_sector_analysis_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sector_analysis', ['sector_analysis_id'], ['id'])

    with op.batch_alter_table('sector_research_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_research_source_sector_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_sector_research_source_source_type'))
        batch_op.drop_constraint(batch_op.f('sector_research_source_sector_analysis_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sector_analysis', ['sector_analysis_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sector_research_source', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sector_research_source_sector_analysis_id_fkey'), 'sector_analysis', ['sector_analysis_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_sector_research_source_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sector_research_source_sector_analysis_id'), ['sector_analysis_id'], unique=False)

    with op.batch_alter_table('sector_research_section', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sector_research_section_sector_analysis_id_fkey'), 'sector_analysis', ['sector_analysis_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_sector_research_section_sector_analysis_id'), ['sector_analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sector_research_section_display_order'), ['display_order'], unique=False)

    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
