"""add research_settings table

Revision ID: 40a9c7639b9f
Revises: c3a7f1d82e49
Create Date: 2026-02-13 21:01:37.044091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a9c7639b9f'
down_revision = 'c3a7f1d82e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active_project_limit', sa.Integer(), nullable=True),
    sa.Column('weight_momentum', sa.Integer(), nullable=True),
    sa.Column('weight_proximity', sa.Integer(), nullable=True),
    sa.Column('weight_staleness', sa.Integer(), nullable=True),
    sa.Column('weight_signal', sa.Integer(), nullable=True),
    sa.Column('momentum_half_life_days', sa.Integer(), nullable=True),
    sa.Column('staleness_peak_days', sa.Integer(), nullable=True),
    sa.Column('stale_warning_days', sa.Integer(), nullable=True),
    sa.Column('stale_warning_min_progress', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_settings')
    # ### end Alembic commands ###
