"""Add onboarding system fields and OnboardingProgress model

Revision ID: 45999cb628b3
Revises: research_journal_intelligence
Create Date: 2025-09-26 23:21:44.593799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45999cb628b3'
down_revision = 'research_journal_intelligence'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('completed_steps', sa.JSON(), nullable=True),
    sa.Column('first_company_name', sa.String(length=200), nullable=True),
    sa.Column('first_company_id', sa.Integer(), nullable=True),
    sa.Column('first_kill_checklist_id', sa.Integer(), nullable=True),
    sa.Column('first_research_template_id', sa.Integer(), nullable=True),
    sa.Column('step_start_times', sa.JSON(), nullable=True),
    sa.Column('step_completion_times', sa.JSON(), nullable=True),
    sa.Column('onboarding_feedback', sa.Text(), nullable=True),
    sa.Column('satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['first_company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['first_kill_checklist_id'], ['kill_checklist.id'], ),
    sa.ForeignKeyConstraint(['first_research_template_id'], ['research_template.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kill_checklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_kill_checklist_evaluations'))
        batch_op.drop_index(batch_op.f('idx_kill_checklist_updated'))

    with op.batch_alter_table('kill_checklist_suggestion', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('responded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_suggestion_checklist_status'))
        batch_op.drop_index(batch_op.f('idx_suggestion_created_at'))
        batch_op.drop_index(batch_op.f('idx_suggestion_effectiveness'))
        batch_op.drop_index(batch_op.f('idx_suggestion_user_status'))
        batch_op.drop_constraint(batch_op.f('kill_checklist_suggestion_kill_checklist_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('kill_checklist_suggestion_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'kill_checklist', ['kill_checklist_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('kill_criterion', schema=None) as batch_op:
        batch_op.alter_column('last_calculated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('last_used',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_kill_criterion_auto_suggested'))
        batch_op.drop_index(batch_op.f('idx_kill_criterion_effectiveness'))
        batch_op.drop_index(batch_op.f('idx_kill_criterion_last_used'))
        batch_op.drop_constraint(batch_op.f('fk_kill_criterion_source_mistake'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'mistake_log', ['source_mistake_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_step', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('preferred_sprint_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('research_experience_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notification_preferences', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('buddy_system_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('peer_feedback_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('community_reputation', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_fomo_alert', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fomo_protection_level', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fomo_protection_level')
        batch_op.drop_column('last_fomo_alert')
        batch_op.drop_column('community_reputation')
        batch_op.drop_column('peer_feedback_count')
        batch_op.drop_column('buddy_system_enabled')
        batch_op.drop_column('notification_preferences')
        batch_op.drop_column('research_experience_level')
        batch_op.drop_column('preferred_sprint_duration')
        batch_op.drop_column('onboarding_completed_at')
        batch_op.drop_column('onboarding_started_at')
        batch_op.drop_column('onboarding_step')
        batch_op.drop_column('onboarding_completed')

    with op.batch_alter_table('kill_criterion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_kill_criterion_source_mistake'), 'mistake_log', ['source_mistake_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_kill_criterion_last_used'), ['last_used'], unique=False)
        batch_op.create_index(batch_op.f('idx_kill_criterion_effectiveness'), ['effectiveness_score'], unique=False)
        batch_op.create_index(batch_op.f('idx_kill_criterion_auto_suggested'), ['auto_suggested'], unique=False)
        batch_op.alter_column('last_used',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('last_calculated',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('kill_checklist_suggestion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('kill_checklist_suggestion_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('kill_checklist_suggestion_kill_checklist_id_fkey'), 'kill_checklist', ['kill_checklist_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_suggestion_user_status'), ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_suggestion_effectiveness'), ['effectiveness_gain'], unique=False)
        batch_op.create_index(batch_op.f('idx_suggestion_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_suggestion_checklist_status'), ['kill_checklist_id', 'status'], unique=False)
        batch_op.alter_column('responded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('kill_checklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_kill_checklist_updated'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_kill_checklist_evaluations'), ['total_ideas_evaluated'], unique=False)

    op.drop_table('onboarding_progress')
    # ### end Alembic commands ###
