"""Add session_history to ResearchProject

Revision ID: 4761422fc789
Revises: 1296ea3ecde2
Create Date: 2026-02-20 15:41:37.099336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4761422fc789'
down_revision = '1296ea3ecde2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_history', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_project', schema=None) as batch_op:
        batch_op.drop_column('session_history')

    # ### end Alembic commands ###
