"""Add FreeResearchQuestion and ModelQuestion models

Revision ID: 50fbe59c23d9
Revises: migrate_abandoned_pass
Create Date: 2026-01-22 19:37:28.488313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fbe59c23d9'
down_revision = 'migrate_abandoned_pass'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_research_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('free_research_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_free_research_question_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_free_research_question_user_id'), ['user_id'], unique=False)

    op.create_table('model_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('source_project_id', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_project_id'], ['research_project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_question_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_question_user_id'))

    op.drop_table('model_question')
    with op.batch_alter_table('free_research_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_free_research_question_user_id'))
        batch_op.drop_index(batch_op.f('ix_free_research_question_project_id'))

    op.drop_table('free_research_question')
    # ### end Alembic commands ###
