"""add ai intelligence tables for research outcomes tracking

Revision ID: 5cab725fd0d5
Revises: rename_checklist_analysis
Create Date: 2025-12-22 06:23:57.794800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '5cab725fd0d5'
down_revision = 'rename_checklist_analysis'
branch_labels = None
depends_on = None


def upgrade():
    # Enable pgvector extension (required for embedding_store table)
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', 'embedding_model', name='uix_embedding_unique')
    )
    with op.batch_alter_table('embedding_store', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embedding_store_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_embedding_store_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_embedding_store_user_id'), ['user_id'], unique=False)

    op.create_table('ml_prediction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('input_features', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('predicted_label', sa.String(length=100), nullable=True),
    sa.Column('prediction_probabilities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('actual_label', sa.String(length=100), nullable=True),
    sa.Column('prediction_error', sa.Float(), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_prediction_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_prediction_log_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_prediction_log_model_version'), ['model_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_prediction_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_prediction_log_was_correct'), ['was_correct'], unique=False)

    op.create_table('ai_insight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('supporting_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('related_mistake_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('related_outcome_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('similar_past_insights', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('was_shown', sa.Boolean(), nullable=True),
    sa.Column('shown_at', sa.DateTime(), nullable=True),
    sa.Column('user_action', sa.String(length=50), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('action_taken_at', sa.DateTime(), nullable=True),
    sa.Column('was_validated', sa.Boolean(), nullable=True),
    sa.Column('validation_outcome', sa.String(length=50), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_insight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_insight_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insight_insight_type'), ['insight_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insight_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insight_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insight_validation_outcome'), ['validation_outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insight_was_validated'), ['was_validated'], unique=False)

    op.create_table('research_outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checklist_analysis_id', sa.Integer(), nullable=True),
    sa.Column('research_project_id', sa.Integer(), nullable=True),
    sa.Column('decision_journal_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('research_quality_score', sa.Float(), nullable=True),
    sa.Column('questions_answered', sa.Integer(), nullable=True),
    sa.Column('questions_total', sa.Integer(), nullable=True),
    sa.Column('documents_analyzed', sa.Integer(), nullable=True),
    sa.Column('ai_assists_used', sa.Integer(), nullable=True),
    sa.Column('research_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('checklist_completion_pct', sa.Float(), nullable=True),
    sa.Column('had_financial_analysis', sa.Boolean(), nullable=True),
    sa.Column('had_competitive_analysis', sa.Boolean(), nullable=True),
    sa.Column('had_management_review', sa.Boolean(), nullable=True),
    sa.Column('had_valuation_model', sa.Boolean(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('position_size', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('initial_thesis', sa.Text(), nullable=True),
    sa.Column('confidence_at_entry', sa.Integer(), nullable=True),
    sa.Column('expected_return_pct', sa.Float(), nullable=True),
    sa.Column('expected_hold_months', sa.Integer(), nullable=True),
    sa.Column('current_return_pct', sa.Float(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('realized_return_pct', sa.Float(), nullable=True),
    sa.Column('actual_hold_days', sa.Integer(), nullable=True),
    sa.Column('thesis_accuracy_score', sa.Float(), nullable=True),
    sa.Column('checkpoints_met', sa.Integer(), nullable=True),
    sa.Column('checkpoints_total', sa.Integer(), nullable=True),
    sa.Column('thesis_still_valid', sa.Boolean(), nullable=True),
    sa.Column('outcome_category', sa.String(length=20), nullable=True),
    sa.Column('predictive_factors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_confidence', sa.Float(), nullable=True),
    sa.Column('lessons_extracted', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('outcome_recorded_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_analysis_id'], ['checklist_analysis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_journal_id'], ['decision_journal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['research_project_id'], ['research_project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_outcome', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_outcome_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_outcome_decision_date'), ['decision_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_outcome_outcome_category'), ['outcome_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_outcome_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('community_reputation')
        batch_op.drop_column('peer_feedback_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peer_feedback_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('community_reputation', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('research_outcome', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_outcome_user_id'))
        batch_op.drop_index(batch_op.f('ix_research_outcome_outcome_category'))
        batch_op.drop_index(batch_op.f('ix_research_outcome_decision_date'))
        batch_op.drop_index(batch_op.f('ix_research_outcome_company_id'))

    op.drop_table('research_outcome')
    with op.batch_alter_table('ai_insight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_insight_was_validated'))
        batch_op.drop_index(batch_op.f('ix_ai_insight_validation_outcome'))
        batch_op.drop_index(batch_op.f('ix_ai_insight_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_insight_is_active'))
        batch_op.drop_index(batch_op.f('ix_ai_insight_insight_type'))
        batch_op.drop_index(batch_op.f('ix_ai_insight_created_at'))

    op.drop_table('ai_insight')
    with op.batch_alter_table('ml_prediction_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_prediction_log_was_correct'))
        batch_op.drop_index(batch_op.f('ix_ml_prediction_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_ml_prediction_log_model_version'))
        batch_op.drop_index(batch_op.f('ix_ml_prediction_log_model_name'))

    op.drop_table('ml_prediction_log')
    with op.batch_alter_table('embedding_store', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embedding_store_user_id'))
        batch_op.drop_index(batch_op.f('ix_embedding_store_entity_type'))
        batch_op.drop_index(batch_op.f('ix_embedding_store_entity_id'))

    op.drop_table('embedding_store')
    # ### end Alembic commands ###
