"""Increase checklist description length to 1000 characters

Revision ID: 64569e8e2992
Revises: 3713b0ccc399
Create Date: 2025-09-16 22:16:01.520239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64569e8e2992'
down_revision = '3713b0ccc399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###
