"""Add BiasCheckResult model for cognitive bias analysis

Revision ID: 6f0b5584e1e2
Revises: 50fbe59c23d9
Create Date: 2026-01-25 11:05:51.736034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0b5584e1e2'
down_revision = '50fbe59c23d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bias_check_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('overall_level', sa.String(length=20), nullable=False),
    sa.Column('excitement_score', sa.Integer(), nullable=False),
    sa.Column('balance_assessment', sa.Text(), nullable=True),
    sa.Column('biases_detected', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('bullish_points', sa.Integer(), nullable=True),
    sa.Column('bearish_points', sa.Integer(), nullable=True),
    sa.Column('risks_acknowledged', sa.Integer(), nullable=True),
    sa.Column('certainty_phrases', sa.Integer(), nullable=True),
    sa.Column('superlatives', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('feedback', sa.String(length=20), nullable=True),
    sa.Column('feedback_at', sa.DateTime(), nullable=True),
    sa.Column('investment_outcome', sa.String(length=20), nullable=True),
    sa.Column('return_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bias_check_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bias_check_result_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bias_check_result_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bias_check_result_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bias_check_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bias_check_result_user_id'))
        batch_op.drop_index(batch_op.f('ix_bias_check_result_project_id'))
        batch_op.drop_index(batch_op.f('ix_bias_check_result_created_at'))

    op.drop_table('bias_check_result')
    # ### end Alembic commands ###
