"""Add market sweep models for Start with As feature

Revision ID: 73ea0f967eb2
Revises: fc700fb034d1
Create Date: 2026-03-05 15:34:54.078980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ea0f967eb2'
down_revision = 'fc700fb034d1'
branch_labels = None
depends_on = None


def _table_exists(table_name):
    """Check if a table already exists in the database."""
    conn = op.get_bind()
    result = conn.execute(
        sa.text("SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = :t)"),
        {"t": table_name}
    )
    return result.scalar()


def upgrade():
    # Tables may already exist if created by db.create_all() before migration ran
    if not _table_exists('market_sweep'):
        op.create_table('market_sweep',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('country', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('total_companies', sa.Integer(), nullable=True),
        sa.Column('uploaded_by', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if not _table_exists('market_sweep_company'):
        op.create_table('market_sweep_company',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sweep_id', sa.Integer(), nullable=False),
        sa.Column('company_name', sa.String(length=300), nullable=False),
        sa.Column('ticker', sa.String(length=50), nullable=True),
        sa.Column('sector_label', sa.String(length=200), nullable=True),
        sa.Column('market_cap', sa.String(length=50), nullable=True),
        sa.Column('exchange', sa.String(length=100), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['sweep_id'], ['market_sweep.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('market_sweep_company', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_market_sweep_company_sort_order'), ['sort_order'], unique=False)
            batch_op.create_index(batch_op.f('ix_market_sweep_company_sweep_id'), ['sweep_id'], unique=False)

    if not _table_exists('market_sweep_decision'):
        op.create_table('market_sweep_decision',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('sweep_company_id', sa.Integer(), nullable=False),
        sa.Column('decision', sa.String(length=20), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('kill_reasons', sa.JSON(), nullable=True),
        sa.Column('sector_id', sa.Integer(), nullable=True),
        sa.Column('promoted_idea_id', sa.Integer(), nullable=True),
        sa.Column('decided_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['promoted_idea_id'], ['idea_pipeline.id'], ),
        sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
        sa.ForeignKeyConstraint(['sweep_company_id'], ['market_sweep_company.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'sweep_company_id', name='_user_sweep_company_uc')
        )
        with op.batch_alter_table('market_sweep_decision', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_market_sweep_decision_sweep_company_id'), ['sweep_company_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_market_sweep_decision_user_id'), ['user_id'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_sweep_decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_sweep_decision_user_id'))
        batch_op.drop_index(batch_op.f('ix_market_sweep_decision_sweep_company_id'))

    op.drop_table('market_sweep_decision')
    with op.batch_alter_table('market_sweep_company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_sweep_company_sweep_id'))
        batch_op.drop_index(batch_op.f('ix_market_sweep_company_sort_order'))

    op.drop_table('market_sweep_company')
    op.drop_table('market_sweep')
    # ### end Alembic commands ###
