"""Add first_research_project_id to onboarding_progress

Revision ID: 74a89e6946b7
Revises: d5acd9da1374
Create Date: 2025-09-27 16:15:12.937630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a89e6946b7'
down_revision = 'd5acd9da1374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_research_project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'research_project', ['first_research_project_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('first_research_project_id')

    # ### end Alembic commands ###
