"""Add AI token tracking columns to User model

Revision ID: 7bd7d4065ba9
Revises: 109bc6695111
Create Date: 2026-01-18 15:14:28.833849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd7d4065ba9'
down_revision = '109bc6695111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_tokens_used', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ai_tokens_limit', sa.Integer(), nullable=False, server_default='10000'))
        batch_op.add_column(sa.Column('ai_tokens_reset_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_ai_tokens_used'), ['ai_tokens_used'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_ai_tokens_used'))
        batch_op.drop_column('ai_tokens_reset_date')
        batch_op.drop_column('ai_tokens_limit')
        batch_op.drop_column('ai_tokens_used')

    # ### end Alembic commands ###
