"""Add checklist confirmation fields to OnboardingProgress

Revision ID: 815df76216d4
Revises: f6ba35466764
Create Date: 2025-09-27 19:10:00.780967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815df76216d4'
down_revision = 'f6ba35466764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('checklist_confirmation_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.drop_column('checklist_confirmation_time')
        batch_op.drop_column('checklist_confirmed')

    # ### end Alembic commands ###
