"""Add reporting_currency to company

Revision ID: 8a4e335a947a
Revises: ce7a4450f981
Create Date: 2026-03-19 21:01:00.078431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4e335a947a'
down_revision = 'ce7a4450f981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporting_currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('reporting_currency')

    # ### end Alembic commands ###
