"""add_description_field_to_checklist_item

Revision ID: 8cb6b829ad88
Revises: 8e7febff91a3
Create Date: 2025-11-16 19:18:29.624367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb6b829ad88'
down_revision = '8e7febff91a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_item', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
