"""Add portfolio_ui_insights table for historical analysis tracking

Revision ID: b5f37db73215
Revises: 6f0b5584e1e2
Create Date: 2026-02-01 15:51:17.255068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f37db73215'
down_revision = '6f0b5584e1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_ui_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('insights_json', sa.JSON(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('position_count', sa.Integer(), nullable=True),
    sa.Column('last_transaction_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_ui_insights')
    # ### end Alembic commands ###
