"""add stale_nudge_days to research_settings

Revision ID: b8bd4bcb76e4
Revises: 40a9c7639b9f
Create Date: 2026-02-14 16:03:34.120826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bd4bcb76e4'
down_revision = '40a9c7639b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stale_nudge_days', sa.Integer(), server_default='21', nullable=True))

    op.execute('UPDATE research_settings SET stale_nudge_days = 21 WHERE stale_nudge_days IS NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_settings', schema=None) as batch_op:
        batch_op.drop_column('stale_nudge_days')

    # ### end Alembic commands ###
