# StartWithA
# Copyright (C) 2024-2026 Kiran Mathews
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""add knowledge_chunk

Revision ID: c85080497f69
Revises: unique_company_ticker
Create Date: 2026-07-24 22:38:15.699396

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'c85080497f69'
down_revision = 'unique_company_ticker'
branch_labels = None
depends_on = None


def upgrade():
    # Only creates knowledge_chunk. Unrelated autogenerated diffs (dropped
    # indexes / constraints on other tables, reflecting pre-existing dev-DB
    # drift) were removed by hand — this migration is scoped to the companion
    # knowledge index alone.
    op.create_table('knowledge_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_knowledge_source')
    )
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunk_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunk_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunk_user_id'), ['user_id'], unique=False)


def downgrade():
    with op.batch_alter_table('knowledge_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunk_user_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunk_source_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunk_company_id'))

    op.drop_table('knowledge_chunk')
