"""Add unique constraint on research_project(user_id, company_id)

Revision ID: cb2ef7d1a47e
Revises: 4761422fc789
Create Date: 2026-02-22 19:07:52.852842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2ef7d1a47e'
down_revision = '4761422fc789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_project', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_research_project_user_company', ['user_id', 'company_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_project', schema=None) as batch_op:
        batch_op.drop_constraint('uq_research_project_user_company', type_='unique')

    # ### end Alembic commands ###
