"""Fix foreign key constraints in onboarding_progress table

Revision ID: d5acd9da1374
Revises: 45999cb628b3
Create Date: 2025-09-27 15:07:08.147585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5acd9da1374'
down_revision = '45999cb628b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('onboarding_progress_first_research_template_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('onboarding_progress_first_company_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('onboarding_progress_first_kill_checklist_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'kill_checklist', ['first_kill_checklist_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'research_template', ['first_research_template_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'company', ['first_company_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('onboarding_progress_first_kill_checklist_id_fkey'), 'kill_checklist', ['first_kill_checklist_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('onboarding_progress_first_company_id_fkey'), 'company', ['first_company_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('onboarding_progress_first_research_template_id_fkey'), 'research_template', ['first_research_template_id'], ['id'])

    # ### end Alembic commands ###
