"""add_atomic_notes_system_sector_sections_and_notes

Revision ID: dbe738d7c27e
Revises: ec749668c93e
Create Date: 2025-10-08 21:53:51.602930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe738d7c27e'
down_revision = 'ec749668c93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_analysis_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sector_analysis_id'], ['sector_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_analysis_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('source_title', sa.String(length=300), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sector_section.id'], ),
    sa.ForeignKeyConstraint(['sector_analysis_id'], ['sector_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sector_note')
    op.drop_table('sector_section')
    # ### end Alembic commands ###
