"""add position tracking fields to transaction model

Revision ID: de438cfe4dc9
Revises: 8cb6b829ad88
Create Date: 2025-11-18 06:03:56.947789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de438cfe4dc9'
down_revision = '8cb6b829ad88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_add_to_position', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('add_position_reason', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('add_position_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('thesis_updated', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transaction_is_add_to_position'), ['is_add_to_position'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_is_add_to_position'))
        batch_op.drop_column('thesis_updated')
        batch_op.drop_column('add_position_notes')
        batch_op.drop_column('add_position_reason')
        batch_op.drop_column('is_add_to_position')

    # ### end Alembic commands ###
