"""add_auth0_fields_to_user_model

Revision ID: e63003c83a60
Revises: f1f78216cc42
Create Date: 2025-10-30 17:17:42.007176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63003c83a60'
down_revision = 'f1f78216cc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('picture', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=50), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_auth0_id'), ['auth0_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_auth0_id'))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('picture')
        batch_op.drop_column('name')
        batch_op.drop_column('auth0_id')

    # ### end Alembic commands ###
