"""add_onboarding_and_tour_tracking_fields

Revision ID: f1f78216cc42
Revises: add_coc_too_hard
Create Date: 2025-10-26 19:13:45.023747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1f78216cc42'
down_revision = 'add_coc_too_hard'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_progress')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_company_sector'))
        batch_op.create_index(batch_op.f('ix_company_sector_id'), ['sector_id'], unique=False)

    with op.batch_alter_table('idea_pipeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_idea_pipeline_sector'))
        batch_op.create_index(batch_op.f('ix_idea_pipeline_sector_id'), ['sector_id'], unique=False)

    with op.batch_alter_table('question_bank_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_question_bank_item_sector'))
        batch_op.create_index(batch_op.f('ix_question_bank_item_sector_id'), ['sector_id'], unique=False)

    with op.batch_alter_table('research_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_research_project_sector'))
        batch_op.create_index(batch_op.f('ix_research_project_sector_id'), ['sector_id'], unique=False)

    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('total_companies',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('companies_analyzed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('companies_invested',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_research_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
        batch_op.alter_column('coc_yes_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('coc_no_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('coc_unsure_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_sector_category'))
        batch_op.drop_index(batch_op.f('idx_sector_slug'))
        batch_op.drop_index(batch_op.f('idx_sector_status'))
        batch_op.drop_index(batch_op.f('idx_sector_user_id'))
        batch_op.create_index(batch_op.f('ix_sector_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_sector_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('sector_analysis', schema=None) as batch_op:
        batch_op.alter_column('sector_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_sector_analysis_sector_id'), ['sector_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_path_chosen', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('page_tours_completed', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tour_preferences', sa.JSON(), nullable=True))
        batch_op.drop_column('onboarding_started_at')
        batch_op.drop_column('onboarding_step')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_step', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('onboarding_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('tour_preferences')
        batch_op.drop_column('page_tours_completed')
        batch_op.drop_column('onboarding_path_chosen')

    with op.batch_alter_table('sector_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_analysis_sector_id'))
        batch_op.alter_column('sector_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_user_id'))
        batch_op.drop_index(batch_op.f('ix_sector_slug'))
        batch_op.create_index(batch_op.f('idx_sector_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_sector_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_sector_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_sector_category'), ['category'], unique=False)
        batch_op.alter_column('coc_unsure_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('coc_no_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('coc_yes_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_research_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
        batch_op.alter_column('companies_invested',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('companies_analyzed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_companies',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))

    with op.batch_alter_table('research_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_project_sector_id'))
        batch_op.create_index(batch_op.f('idx_research_project_sector'), ['sector_id'], unique=False)

    with op.batch_alter_table('question_bank_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_bank_item_sector_id'))
        batch_op.create_index(batch_op.f('idx_question_bank_item_sector'), ['sector_id'], unique=False)

    with op.batch_alter_table('idea_pipeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_pipeline_sector_id'))
        batch_op.create_index(batch_op.f('idx_idea_pipeline_sector'), ['sector_id'], unique=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_sector_id'))
        batch_op.create_index(batch_op.f('idx_company_sector'), ['sector_id'], unique=False)

    op.create_table('onboarding_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('first_company_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('first_company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_kill_checklist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_research_template_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('step_start_times', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('step_completion_times', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('onboarding_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('satisfaction_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_research_project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('onboarding_research_answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('onboarding_structured_answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('checklist_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('checklist_confirmation_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['first_company_id'], ['company.id'], name=op.f('onboarding_progress_first_company_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_kill_checklist_id'], ['kill_checklist.id'], name=op.f('onboarding_progress_first_kill_checklist_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_research_project_id'], ['research_project.id'], name=op.f('onboarding_progress_first_research_project_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_research_template_id'], ['research_template.id'], name=op.f('onboarding_progress_first_research_template_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('onboarding_progress_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('onboarding_progress_pkey'))
    )
    # ### end Alembic commands ###
