"""add_portfolio_transaction_and_position_models

Revision ID: f28d03104087
Revises: e63003c83a60
Create Date: 2025-11-01 17:43:15.939684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28d03104087'
down_revision = 'e63003c83a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('average_cost_basis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unrealized_gain_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unrealized_gain_loss_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('realized_gain_loss', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('realized_gain_loss_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('first_purchase_date', sa.Date(), nullable=True),
    sa.Column('last_transaction_date', sa.Date(), nullable=True),
    sa.Column('last_price_update', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company_position')
    )
    with op.batch_alter_table('portfolio_position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_position_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_position_first_purchase_date'), ['first_purchase_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_position_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_position_user_id'), ['user_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('decision_journal_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('bought_without_research', sa.Boolean(), nullable=True),
    sa.Column('reason_without_research', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['decision_journal_id'], ['decision_journal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_bought_without_research'), ['bought_without_research'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('decision_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_portfolio_decision', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('linked_research_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_decision_journal_is_portfolio_decision'), ['is_portfolio_decision'], unique=False)
        batch_op.create_foreign_key(None, 'research_project', ['linked_research_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_journal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_decision_journal_is_portfolio_decision'))
        batch_op.drop_column('linked_research_id')
        batch_op.drop_column('is_portfolio_decision')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_company_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_bought_without_research'))

    op.drop_table('transaction')
    with op.batch_alter_table('portfolio_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_position_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_position_is_active'))
        batch_op.drop_index(batch_op.f('ix_portfolio_position_first_purchase_date'))
        batch_op.drop_index(batch_op.f('ix_portfolio_position_company_id'))

    op.drop_table('portfolio_position')
    # ### end Alembic commands ###
