"""Add onboarding research answers fields to OnboardingProgress

Revision ID: f6ba35466764
Revises: 74a89e6946b7
Create Date: 2025-09-27 16:21:41.124557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ba35466764'
down_revision = '74a89e6946b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_research_answers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('onboarding_structured_answers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.drop_column('onboarding_structured_answers')
        batch_op.drop_column('onboarding_research_answers')

    # ### end Alembic commands ###
