"""Add AI consent fields to User model for GDPR

Revision ID: fc700fb034d1
Revises: e788f90c2893
Create Date: 2026-03-01 22:03:07.364896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc700fb034d1'
down_revision = 'e788f90c2893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_consent_given', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_consent_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ai_consent_date')
        batch_op.drop_column('ai_consent_given')

    # ### end Alembic commands ###
